#Task 1 — Load the Data

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
df.shape

(1338, 7)

#Task 2 — Get the Quick Summary

In [5]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

1. charges has the highest mean value
2. charges has the biggest bag
3. mean is higher than median. this mean the data has a couple outliers on the right side.

#Task 3 — Center and Spread for One Column

In [12]:
print("mean:", df['bmi'].mean())
print("median:", df['bmi'].median())
print("minimum:", df['bmi'].min())
print("maximum:", df['bmi'].max())
print("standard deviation:", df['bmi'].std())

mean: 30.66339686098655
median: 30.4
minimum: 15.96
maximum: 53.13
standard deviation: 6.098186911679017

1. The mean and median is close. The shape of the distrubution will look like a bell.